# No ambiente Docker, salva os logs em /app/logs (mapeado como volume no docker-compose)
logging.file.name=/app/logs/metric-manager.log
logging.logback.rollingpolicy.file-name-pattern=/app/logs/metric-manager-%d{yyyy-MM-dd}.%i.log
logging.logback.rollingpolicy.max-file-size=10MB
logging.logback.rollingpolicy.max-history=30
logging.logback.rollingpolicy.total-size-cap=200MB
